name: product-catalouge-ci
on:
  pull_request:
    branches:
      - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v4
            - name: setup GO
              uses: actions/setup-go@v2
              with:
               go-version: 1.22
            - name: install dependencies
              run: go mod download src/product-catalog
            - name: build
              run: go build src/product-catalog main.go
            - name: test
              run: go test src/product-catalog
    static_code_analysis:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v4
            - name: setup GO
              uses: actions/setup-go@v2
              with:
               go-version: 1.22
            - name: setup golanglint-ci
              uses: golangci/golangci-lint-action@v6
              with:
                version: v1.55.2
                run: golangci-lint run 
                working-directory: src/product-catalog
    Docker:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: code checkout
              uses: actions/checkout@v4
            - name: setup docker
              uses: docker/setup-buildx-action@v1
            - name: docker login
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}
            - name: build docker image
              uses: docker/build-push-action@v6
              with:
                context: src/product-catalog
                file: src/product-catalog/Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/product-catalouge:${{ github.run_id }}
    update_k8s:
        runs-on: ubuntu-latest
        needs: Docker
        steps:
            - name: code checkout
              uses: actions/checkout@v4
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
            - name: update image tag in deployment file
              run: |
                sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.run_id }}|" kubernetes/productcatalog/deploy.yaml
            - name: commit and push changes
              run: |
                git config --global user.email "venkyravipati99@gmail.com"
                git config --global user.name "Mohan Venkatesh"
                git add kubernetes/productcatalog/deploy.yaml
                git commit -m "CI []: update image tag"
                git push origin HEAD:main -f